### ISSUE TITLE
Heading alignment is need on left side 

### ISSUE THREAD

**Issue by the-macson** [DSC-JSS-NOIDA/QuickLearn#223]
Heading alignment should be on the left side not on the center and heading of start learning is also on be left side but it's on center
![Screenshot (114)](https://user-images.githubusercontent.com/71259159/160987453-02ce498c-98a7-44f2-be75-11e64153f4c3.png)
![Screenshot (115)](https://user-images.githubusercontent.com/71259159/160987463-e4482290-39cf-42db-91bc-cd4de72c18b3.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 11]
 - Browser [chrome]

**Comment by fakoredeDamilola** [comment]
can I work in this

**Comment by the-macson** [comment]
okay @fakoredeDamilola 
I am assigning to you

**Comment by Rishita489** [comment]
Hey , @the-macson , I am GSSOC'22 contributor . I have solved the issue and also attached the screenshots below . Can you please assign this issue to me so that I can send the PR . 
![image](https://user-images.githubusercontent.com/73689669/161216583-2ab1b561-c8f6-476b-9cb5-0a5c9268861c.png)
![image](https://user-images.githubusercontent.com/73689669/161216672-e6874dd9-1698-4822-acb4-8b82a4bd44b1.png)

**Comment by the-macson** [comment]
Okay I am assigning to you @Rishita489

**Comment by Abhay2002r** [comment]
hey, @the-macson  I already sent a pull request to you, Please let me know if there are any issues you found !!

**Comment by Rishita489** [comment]
Ok I will send the PR . You please review and merge it .

**Comment by Abhay2002r** [comment]
hey @the-macson, I have solved my issue, please review and merge it.

**Comment by Rishita489** [comment]
hey @the-macson , I am assigned this issue and I have send the PR , please review and merge it .

**Comment by the-macson** [comment]
okay
