### ISSUE TITLE
Adding Images in resources section

### ISSUE THREAD

**Issue by aaryahjolia** [DSC-JSS-NOIDA/QuickLearn#277]
**Is your feature request related to a problem? Please describe.**
I will be happy to see images of websites offering courses or images of the course itself as it will enable me to get the information widely.

**Describe the solution you'd like**
I want to add images of different courses and mooc platforms to resources page as it will look perfect instead of the default image that occurs in every course.

**Additional context**

![GSSoC](https://user-images.githubusercontent.com/82600388/165976824-c93a8dd3-621c-429b-8659-9c7c2caea2ec.png)

**Comment by aaryahjolia** [comment]
I want to do like this : 

![image](https://user-images.githubusercontent.com/82600388/166447997-b23a661a-b279-45e7-90e0-20097ea9e15f.png)

Should I move ahead ?

**Comment by rucha0702** [comment]
@aaryahjolia we can't have different images for all the resources, since there is no separate key for the image, but there is a key that differentiates videos and docs, so we can have two separate images depending upon docs and videos. Currently, the image for docs seems fine, we only need to change it for the video resources. Changes are to be made only in the for loop.

**Comment by aaryahjolia** [comment]
Is this fine ? It also matches somewhat the other image for docs

![image](https://user-images.githubusercontent.com/82600388/166482395-059c597f-8755-40fd-8c4e-e6656ea8fbee.png)

For the approach, Instead of changing image name in for loop, I replaced the old image with this new one with same name as old one. Mention the changes that needs to be done or I should make a PR.

**Comment by rucha0702** [comment]
Create a PR
